### ISSUE TITLE
运行AnyBURL生成规则时报错 

### ISSUE THREAD

**Issue by sana-mine** [bys0318/SQUIRE#3]
你好，我想问一下这个path-1000是不是没有给出来呢？

File "utils.py", line 34, in filter_rule
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'path1/path-1000'

**Comment by bys0318** [comment]
请先在AnyBURL/文件夹下创建名为path1的文件夹，然后再运行run.sh应该就没问题了
