### ISSUE TITLE
可以分享一下rules.dict文件吗

### ISSUE THREAD

**Issue by RongchuanTang** [bys0318/SQUIRE#4]
Yushi你好，对你的这篇工作很感兴趣，不知道是否可以分享一下AnyBURL生成的rules.dict文件，没用过AnyBURL，十分感谢！

**Comment by bys0318** [comment]
没问题，我已经将几个数据集的rules.dict上传在data/下了。

**Comment by RongchuanTang** [comment]
非常感谢！！！
