### ISSUE TITLE
为什么论文中提到的benchmark模型的实验结果比它们原文中的好那么多？

### ISSUE THREAD

**Issue by smc0314** [bys0318/SQUIRE#5]
为什么论文中提到的benchmark模型的实验结果比它们原文中的好那么多？

**Comment by bys0318** [comment]
请问你是指哪个模型呢？

**Comment by smc0314** [comment]
> 请问你是指哪个模型呢？

比如ConvE模型，原文中在FB15k-237数据集上的hit@1最好为0.237，而在您的论文中为0.342，其它几个模型TransE、RotatE等在您的论文中实现效果也普遍偏高很多

**Comment by bys0318** [comment]
我们的实验评估只预测尾实体，这一块与KGE相关工作不同（KGE相关工作评测时同时预测头尾实体并将结果取平均），我们的实验评测follow了之前的multi-hop reasoning工作的设定。
